# numpy basics

In [ ]:
my_array=[1,2,3]
my_array

In [4]:
import numpy as np

In [ ]:
np_array = np.array(my_array)
np_array
type(np_array)

In [7]:
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [8]:
np_matrix = np.array(my_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np_matrix.shape

(2, 3)

In [10]:
#operations

new_arr = np.array([1,2,3])
new_arr2 = np.array([4,5,6])

In [ ]:
np.add(new_arr,new_arr2)

In [ ]:
np.subtract(new_arr,new_arr2)

In [ ]:
np.multiply(new_arr,new_arr2)

In [11]:
np.divide(new_arr,new_arr2)

array([0.25, 0.4 , 0.5 ])

In [ ]:
new_arr + new_arr2

In [ ]:
new_arr - new_arr2

In [ ]:
new_arr * new_arr2

In [ ]:
new_arr / new_arr2

In [ ]:
new_arr / 2

In [ ]:
## indexing and selection

In [12]:
my_2d_array = [[4,15,20],[1,0,-10],[52,11,9.56],[2,8,4],[8,7,3]]
my_2d_array

[[4, 15, 20], [1, 0, -10], [52, 11, 9.56], [2, 8, 4], [8, 7, 3]]

In [13]:
my_2d_array[1]

[1, 0, -10]

In [14]:
my_2d_np_array = np.array(my_2d_array)
my_2d_np_array

array([[  4.  ,  15.  ,  20.  ],
       [  1.  ,   0.  , -10.  ],
       [ 52.  ,  11.  ,   9.56],
       [  2.  ,   8.  ,   4.  ],
       [  8.  ,   7.  ,   3.  ]])

In [15]:
my_2d_np_array[1]

array([  1.,   0., -10.])

In [16]:
my_2d_np_array[0][2]

20.0

In [17]:
my_2d_np_array[0,2]

20.0

In [18]:
my_2d_np_array[0:2]

array([[  4.,  15.,  20.],
       [  1.,   0., -10.]])

In [20]:
my_2d_np_array

array([[  4.  ,  15.  ,  20.  ],
       [  1.  ,   0.  , -10.  ],
       [ 52.  ,  11.  ,   9.56],
       [  2.  ,   8.  ,   4.  ],
       [  8.  ,   7.  ,   3.  ]])

In [25]:
my_2d_np_array[2:4,0:2]

array([[52.  , 11.  ,  9.56],
       [ 2.  ,  8.  ,  4.  ]])

In [ ]:
my_2d_np_array[2:4,::2]

In [26]:
my_2d_np_array

array([[  4.  ,  15.  ,  20.  ],
       [  1.  ,   0.  , -10.  ],
       [ 52.  ,  11.  ,   9.56],
       [  2.  ,   8.  ,   4.  ],
       [  8.  ,   7.  ,   3.  ]])

In [ ]:
##conditional selection

In [28]:
bool_data = my_2d_np_array > 10
bool_data

array([[False,  True,  True],
       [False, False, False],
       [ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [29]:
my_2d_np_array[my_2d_np_array > 10]

array([15., 20., 52., 11.])

In [31]:
my_2d_np_array[bool_data]

array([15., 20., 52., 11.])

In [30]:
my_2d_np_array[my_2d_np_array > 50]

array([52.])

In [ ]:
##methods

In [32]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
##check for methods ones() and eye() 

In [37]:
np.random.rand(10)

array([0.1533381 , 0.74545989, 0.14264129, 0.68032333, 0.76009689,
       0.86936229, 0.67344044, 0.90570236, 0.01544566, 0.2635358 ])

In [38]:
np.random.rand(5,5)

array([[0.17691853, 0.83997596, 0.00899204, 0.17303593, 0.62939596],
       [0.72777967, 0.9452026 , 0.21391153, 0.81662491, 0.71350416],
       [0.23967044, 0.50843502, 0.48544512, 0.73737423, 0.30423053],
       [0.58603751, 0.52509684, 0.45067902, 0.25804344, 0.96259295],
       [0.6984448 , 0.40909447, 0.1230852 , 0.11149637, 0.6360999 ]])

In [39]:
random_array=np.random.randint(5,15,10)
random_array

array([13, 10, 11, 13, 10,  6,  5, 11, 11,  6])

In [ ]:
my_arr = np.arange(50)
my_arr

In [40]:
random_array=np.random.randint(5,99,15) 
random_array

array([96, 35, 49,  9, 30, 21, 95, 61, 50, 83, 34, 88, 87, 30, 84])

In [41]:
random_array.max()

96

In [42]:
random_array.min()

9

In [43]:
random_array.argmax()

0

In [44]:
random_array.argmin()

3

In [ ]:
random_array.shape

In [47]:
random_array.reshape(3,5)

array([[96, 35, 49,  9, 30],
       [21, 95, 61, 50, 83],
       [34, 88, 87, 30, 84]])

In [48]:
random_array.dtype

dtype('int32')

In [49]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
## data manipulation

In [50]:
random_array[:3] = 2
random_array

array([ 2,  2,  2,  9, 30, 21, 95, 61, 50, 83, 34, 88, 87, 30, 84])

In [ ]:
random_sliced_array = random_array[:6]
random_sliced_array

In [ ]:
random_sliced_array[:2] = 5
random_sliced_array

In [ ]:
random_array

In [51]:
random_sliced_array = random_array.copy() ##creates copy
random_sliced_array

array([ 2,  2,  2,  9, 30, 21, 95, 61, 50, 83, 34, 88, 87, 30, 84])

In [ ]:
random_sliced_array[:2] = 10
random_sliced_array

In [ ]:
random_array

In [62]:
np.full((2,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [63]:
my_2d_array = []
my_2d_array

[[4, 15, 20], [1, 0, -10], [52, 11, 9.56], [2, 8, 4], [8, 7, 3]]

In [65]:
a=np.array([[4,15,20],[1,0,-10],[52,11,9.56],[2,8,4],[8,7,3]])

In [67]:
np.n

array([[  4.  ,  15.  ,  20.  ],
       [  1.  ,   0.  , -10.  ],
       [ 52.  ,  11.  ,   9.56],
       [  2.  ,   8.  ,   4.  ],
       [  8.  ,   7.  ,   3.  ]])

In [69]:
a.mean()

8.970666666666666

In [71]:
a.std()

13.309897804098856

In [73]:
np.mean(a)

8.970666666666666

In [75]:
np.median(a)

7.0

In [78]:
np.mean(a[0])

13.0

In [85]:
sal=np.array([[1,2,3,4,6,"7",8]])

In [86]:
sal*2

TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

In [84]:
np.median(sal)

4.0

In [87]:
np.loadtxt()

TypeError: loadtxt() missing 1 required positional argument: 'fname'

In [91]:
bin(10)

'0b1010'